Recruit_task/Recruit_task/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
   url(r'^admin/', admin.site.urls),
   url(r'^', include('Student_marks.urls'))
]

Recruit_task/Student_marks/urls.py
from django.conf.urls import url, include
from .import views

app_name = 'Student_marks'

urlpatterns = [
   url(r'^$', views.index, name="index"),
   url(r'^extra/$', views.extra_view, name="extra_view"),

]

Recruit_task/Student_marks/models.py
from django.db import models


class Section(models.Model):
   section_name = models.CharField(max_length=100)

   def __str__(self):
      return self.section_name


class Student(models.Model):
   sec = models.ForeignKey(Section, on_delete=models.CASCADE)
   student_name = models.CharField(max_length=100)
   student_score = models.IntegerField(default=0)

   def __str__(self):
      return self.student_name + "-" + str(self.student_score)



Recruit_task/Student_marks/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import Section, Student

# main webpage display view
def index(request):
   all_sections = Section.objects.all()
   student_name = Student.student_name

   required = {
     'all_sections': all_sections,
     'student_name': student_name, 
   }
   return render(request, 'Student_marks/index.html', required)


# increases marks after clicking link button 
# based on if conditions
def extra_view(request):
   all_students = Student.objects.all()

   for student in all_students:
     if 29 <= student.student_score <= 35:
         student.student_score += 7
         student.save()
   return HttpResponseRedirect("/")

Recruit_task/templates/Student_marks/index.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <title>Marks</title>
</head>
<body>
   {% for section in all_sections %}
      <b> {{section}} </b><br>

      {% for student in section.student_set.all %}
         {{student.student_name}}---{{student.student_score}}<br>
      {% endfor %}

   {% endfor %}

   <a href="{% url 'Student_marks:extra_view' %}">Extra</a>
</body>
</html>